# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_auto_20170911_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
