# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_myuser_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='Limitsiz oynaya bilər'),
        ),
    ]
