# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0005_myuser_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='game_session',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
