# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0006_myuser_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='point_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='point_week',
            field=models.IntegerField(default=0),
        ),
    ]
