# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0007_auto_20170913_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='exclude_question',
            field=models.TextField(default='[]'),
        ),
    ]
