# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0008_myuser_exclude_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='social_share_count',
            field=models.IntegerField(default=0),
        ),
    ]
