# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0011_myuser_result_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='share_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
