# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0012_myuser_share_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='share_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
