# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0013_auto_20170929_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='monthly_leaderboard',
            field=models.BooleanField(default=False, help_text='Bu istifadəçi Aylıq Liderborda düşmür'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='weekly_leaderboard',
            field=models.BooleanField(default=False, help_text='Bu istifadəçi Həftəlik Liderborda düşmür'),
        ),
    ]
