# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0014_auto_20171009_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
