# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0015_myuser_full_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='aditional_chance',
            field=models.BooleanField(default=False, help_text='Əlavə oyun oynamağını təmin edir. Oyun sayı əlavə edən zaman aktivləşdirmək vacibdir'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='aditional_games_count',
            field=models.IntegerField(default=0, help_text='Əlavə oyunların sayı'),
        ),
    ]
