# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',), 'verbose_name': 'Sual', 'verbose_name_plural': 'Suallar'},
        ),
        migrations.AlterField(
            model_name='rightanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Question'),
        ),
    ]
