# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170808_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='rightanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RightAnswer',
        ),
    ]
