# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_userquestionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionhistory',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserQuestionHistory',
        ),
    ]
