# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_userquestionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
