# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:57
from __future__ import unicode_literals

import base_user.tools.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170809_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base_user.tools.common.get_answer_photo),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base_user.tools.common.get_question_photo),
        ),
    ]
