# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170810_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
