# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gametime_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='change_question_joker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gametime',
            name='half_question_joker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gametime',
            name='two_question_joker',
            field=models.BooleanField(default=False),
        ),
    ]
