# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
