# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gametime_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametime',
            name='answer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
