# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20170911_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='last_done',
            field=models.BooleanField(default=False),
        ),
    ]
