# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_gametime_last_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='game_session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
