# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_repeating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametime',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
