# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20170913_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='over',
            field=models.BooleanField(default=True),
        ),
    ]
