# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_gametime_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='two_question_joker_expired',
            field=models.BooleanField(default=False),
        ),
    ]
