# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_gametime_two_question_joker_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBoard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.LeaderBoard')),
                ('month_name', models.CharField(max_length=255)),
            ],
            bases=('games.leaderboard',),
        ),
        migrations.CreateModel(
            name='WeekBoard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.LeaderBoard')),
                ('week_name', models.CharField(max_length=255)),
            ],
            bases=('games.leaderboard',),
        ),
    ]
