# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20170923_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month_name', models.CharField(max_length=255)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameTime')),
            ],
        ),
        migrations.CreateModel(
            name='WeekBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('week_name', models.CharField(max_length=255)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameTime')),
            ],
        ),
    ]
