# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 00:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_monthlyresults_weeklyresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(default='all', max_length=255)),
            ],
        ),
    ]
