# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_leaderresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyresults',
            options={'ordering': ('id',), 'verbose_name': 'Həftəlik nəticə', 'verbose_name_plural': 'Həftəlik nəticələr'},
        ),
    ]
