# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20171009_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyresults',
            options={'ordering': ('id',), 'verbose_name': 'Aylıq nəticə', 'verbose_name_plural': 'Aylıq nəticələr'},
        ),
    ]
